### PR TITLE
Week3 rootulp

### PR DESCRIPTION
**Pull request by rootulp**

### CODE REVIEW

**Comment by CoolDude53** [comment]
Nice solution, procedurally very similar to mine. It seems like creating new Strings in your sort method is unnecessary, as you can just compare the two char arrays, but I'd be curious as to why you chose to do so, if for any reason other than readability.

**Comment by rootulp** [comment]
@CoolDude53 To be honest, I copied over this solution from a previous challenge. You make a really good point about comparing char[] rather than creating a new String.

**Comment by rootulp** [comment]
@Aniketsaoji I don't think you should merge PR's that are still being discussed

**Comment by Aniketsaoji** [comment]
Oh shoot, I'm sorry. I'm very new to this all. I just merged them because I thought it was a new solution and it was fine. Didn't realize that we didn't accept the pull request yet.

**Comment by rootulp** [comment]
Totally fine, it's really not a big deal. I just wanted to include the changes proposed by @CoolDude53 in this PR. I probably could have done so if I reverted your merge properly but I ended up including them in a separate PR #10 

In terms of good code review practices, it's probably best to sign off with a [ready to merge](https://github.com/thoughtbot/guides/tree/master/code-review#reviewing-code) comment

**Pull request merged**
